<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite_test" duration-ms="19744" started-at="2019-10-13T16:45:03Z" finished-at="2019-10-13T16:45:23Z">
    <groups>
    </groups>
    <test name="Validate Welcome Page Elements" duration-ms="19744" started-at="2019-10-13T16:45:03Z" finished-at="2019-10-13T16:45:23Z">
      <class name="basicSample.ValidatePopUp">
        <test-method status="PASS" signature="initialize()[pri:0, instance:basicSample.ValidatePopUp@212b5695]" name="initialize" is-config="true" duration-ms="13873" started-at="2019-10-13T09:45:03Z" finished-at="2019-10-13T09:45:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="validate_switch_to_child_get_title()[pri:1, instance:basicSample.ValidatePopUp@212b5695]" name="validate_switch_to_child_get_title" duration-ms="4184" started-at="2019-10-13T09:45:17Z" finished-at="2019-10-13T09:45:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_switch_to_child_get_title -->
        <test-method status="FAIL" signature="validate_switch_to_child_and_fill_data()[pri:2, instance:basicSample.ValidatePopUp@212b5695]" name="validate_switch_to_child_and_fill_data" duration-ms="599" started-at="2019-10-13T09:45:21Z" finished-at="2019-10-13T09:45:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The email and password you entered did not match our records. Please double-check and try again] but found [The email and password you entered did not match our records. Please double-check and try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The email and password you entered did not match our records. Please double-check and try again] but found [The email and password you entered did not match our records. Please double-check and try again.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at basicSample.ValidatePopUp.validate_switch_to_child_and_fill_data(ValidatePopUp.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_switch_to_child_and_fill_data -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:basicSample.ValidatePopUp@212b5695]" name="tearDown" is-config="true" duration-ms="609" started-at="2019-10-13T09:45:22Z" finished-at="2019-10-13T09:45:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- basicSample.ValidatePopUp -->
    </test> <!-- Validate Welcome Page Elements -->
  </suite> <!-- Suite_test -->
</testng-results>
